# 一行最多 120 字符
printWidth: 120
# 使用 2 个空格缩进
tabWidth: 2
# 不使用缩进符，而使用空格
useTabs: false
# 行尾需要分号
semi: true
# 使用单引号
singleQuote: true
# 对象的 key 仅在必要时用引号
quoteProps: as-needed
# 末尾需要逗号
trailingComma: all
# 大括号内的首尾需要空格
bracketSpacing: true
# 箭头函数参数始终带括号
arrowParens: always
# 换行符使用 lf
endOfLine: lf
# 后缀文件名特有规则
overrides:
  - files: '*.{wxss,less}'
    options:
      parser: less
  - files: '*.{wxml,html}'
    options:
      parser: html
      htmlWhitespaceSensitivity: strict
  - files: '*.wxs'
    options:
      parser: babel
